---
show-messages-onjoin: false
force-hub: false
enable-hub-message: true
force-spawn: false
enable-spawn-message: true
enable-aliases: false
teleport-on-death: 2
hub-server:
  enabled: false
  name: External Server
  host: 127.0.0.1
  port: 19132
hub:
  world: hub
  X: 64.500000
  "Y": 156.000000
  Z: 67.500000
  Yaw: 195.035614
  Pitch: 13.928955
...
