---
Positions:
- world: hub
  x: 45
  "y": 154
  z: 36
Update-Interval: 60
Header: §l§6● §dTop§c Đảo §aL§cO§aL§6 ●
text: |-
  §c§l↣ §f[§cTOP 1§f] §r§brichhaogaming:§a 3 lv
  §c§l↣ §f[§cTOP 2§f] §r§bdzsenpai:§a 2 lv
  §c§l↣ §f[§cTOP 3§f] §r§bbidiedart:§a 1 lv
  §c§l↣ §f[§cTOP 4§f] §r§btuilachimbe:§a 1 lv
  §c§l↣ §f[§cTOP 5§f] §r§brichhaogaming2:§a 1 lv
...
