---
# AutoClearLagg (ACL) Config

# Seconds between each clear lagg
seconds: 14400

# Entities to clear
clear:
  items: true
  mobs: true
  xp-orbs: true
  exempt: # Array of entities not to clear
    - Zombie
    - Pig

messages:
  time-left: "§f[ §b§lSκʏ§aL§cO§aL§f ] §fDọn item rơi trên mặt đất sau§9 {SECONDS}s nữa"
  entities-cleared: "§f[ §b§lSκʏ§aL§cO§aL§f ] §7Dọn thành công§f {COUNT} item"

# Countdown times
times: [60, 30, 15, 3, 2, 1]
...
